-- like operator :===

select * from employee;
select * from employee where fname like '%a';
select * from employee where lname like 'a%';
select * from employee where lname like '%y';
select * from employee where fname like 'y%';
select * from employee where fname like '%i%';
select * from employee where dept like '__';
select * from employee where fname like '_i%';


-- aggrigation function   : count, sum, max, min,avg :==

select count(emp_id) from employee;
select count(fname) from employee;

select sum(salary) from employee;
select avg(salary) from employee;
select min(salary) from employee;
select max(salary) from employee;


-- Group by :==

select dept from employee group by dept;
select dept, count(fname)from employee group by dept;
select dept,count(emp_id) from employee group by dept;

select dept,sum(salary) from employee group by dept;


-- String function :==
-- CONCAT,CONCAT_WS
-- SUBSTR
-- LEFT,RIGHT
-- LENGTH
-- UPPER,LOWER
-- TRIM,LTRIM,RTRIM
-- REPLACE
-- POSITION
-- STRING_AGG

SELECT CONCAT('HELLO','WORLD');

SELECT * FROM EMPLOYEE;
SELECT CONCAT(FNAME,LNAME) FROM EMPLOYEE;
SELECT CONCAT(FNAME,LNAME) AS FULLNAME FROM EMPLOYEE;
SELECT EMP_ID,CONCAT(FNAME,LNAME) AS FULLNAME FROM EMPLOYEE;
SELECT EMP_ID,CONCAT(FNAME,LNAME) AS FULLNAME ,DEPT FROM EMPLOYEE;

-- CONCAT_WS(SEPERATOR) FUNCTION:==
SELECT EMP_ID,CONCAT(FNAME,' ',LNAME) AS FULLNAME, DEPT FROM EMPLOYEE;
SELECT CONCAT_WS(':','ONE','TWO','THREE');
SELECT CONCAT_WS('_','ONE','TWO','THREE');
SELECT CONCAT_WS('-','ONE','TWO','THREE');
SELECT CONCAT_WS(' ',FNAME,LNAME) AS FULLNAME FROM EMPLOYEE;

-- SUBSTR(SUBSTRING) FUNCTION:===

SELECT SUBSTRING('HELLO BUDDY',1,4);
SELECT SUBSTRING('HELLO BODDY',1,6);
SELECT SUBSTRING('HELLO BODDY',7,12);

-- REPLACE FUNCTION :==
SELECT REPLACE('ABCXYZ','ABC','PQR');
SELECT REPLACE(DEPT,'IT','TECH')FROM EMPLOYEE;

-- REVERSE FUNCTION :==
SELECT REVERSE('HELLO');
SELECT REVERSE(FNAME) FROM EMPLOYEE;

-- LENGTH FUNCTION:==
SELECT LENGTH('HELLO WORLD');
SELECT LENGTH(FNAME) FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE LENGTH(FNAME)>7;

-- UPPER AND LOWER FUNCTION :==

SELECT UPPER(FNAME) FROM EMPLOYEE;
SELECT LOWER(LNAME) FROM EMPLOYEE;

-- LEFT AND RIGHT FUNCTION :==

SELECT LEFT('HELLO WORLD',4);
SELECT RIGHT('HELLO WORLD',5);
SELECT RIGHT(FNAME,5) FROM EMPLOYEE;

-- TRIM FUNCTION:==

SELECT TRIM('  ALRIGHT  ');
SELECT LENGTH('    ALRIGHT   ');
SELECT LENGTH(TRIM('   ALRIGHT   '));

-- POSITION FUNCTION :==

SELECT POSITION('OM' IN 'TKOMAS');

-- STRING_AVG :==
SELECT STRING_AVG('LOVELY DUBEY');

-- 1. TASK == GIVE ME 1:FNAME:LNAME:DEPT

SELECT CONCAT_WS(':',EMP_ID,FNAME,LNAME,DEPT) FROM EMPLOYEE WHERE EMP_ID =1;

-- 2 TASK ==
SELECT CONCAT_WS(':',EMP_ID, CONCAT_WS(':',FNAME, 'LNAME'),DEPT) FROM EMPLOYEE;

-- 3. TASK == 4:Suman:FINACE

SELECT CONCAT_WS(':', FNAME, UPPER(DEPT)) FROM EMPLOYEE WHERE EMP_ID =4;

-- 4. I1 Raju
--     h2 Priya

SELECT CONCAT(LEFT(DEPT, 1),EMP_ID) FROM EMPLOYEE;

-- 5. FIND DIFFERENCE TYPES OF DEPARTMENTS IN DATABASE?
-- 6. DISPLAY RECORDS WITH HIGH-LOW SALARY?
-- 7. HOW TO SEE ONLY TOP 3 RECORDS FROM A TABLE?
-- 8. SHOW RECORDS WHERE FIRST NAME START WITH LETTER 'A'?
-- 9. SHOW RECORDS WHERE LENGTH OF THE LNAME IS 4 CHARACTER ?


SELECT * FROM EMPLOYEE ORDER BY(SALARY)DESC;
SELECT * FROM employeeLIMIT 3;
SELECT *FROM EMPLOYEE WHERE FNAME LIKE '%A';
SELECT * FROM EMPLOYEE WHERE LENGTH(FNAME)>4;


-- 10. FIND TOTAL NO. OF EMPOLYEE IN DATABASE?
-- 11. FIND NO. OF EMPLOYEE IN EACH DEPARTMENT?
-- 12. FIND LOWEST SALARY PAYING?
-- 13.FIND TOTAL SALARY PAYING IN LOAN DEPARTMENT?
-- 14. AVERAGE SALARY PAYING IN EACH DEPARTMENT?


SELECT COUNT(EMP_ID) FROM EMPLOYEE;
SELECT MIN(SALARY) FROM EMPLOYEE;
SELECT MAX(SALARY) FROM EMPLOYEE;
SELECT SUM(SALARY)FROM EMPLOYEE WHERE DEPT ='HR';
SELECT * FROM EMPLOYEE ORDER BY(SALARY) DESC LIMIT 1;


-- SUBQUERY :==QUERY INSIDE A QUERY
SELECT * FROM EMPLOYEE
WHERE
SALARY=(SELECT MAX(SALARY) FROM EMPLOYEE);

SELECT * FROM EMPLOYEE
WHERE
SALARY =(SELECT MIN(SALARY)FROM EMPLOYEE);

-- ALTERING TABLE : == HOW TO MODIFY TABLE :==
CREATE TABLE Person (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    age INT,
    city VARCHAR(50)
);
SELECT * FROM PERSON;

INSERT INTO Person (id, name, age, city) VALUES
(1, 'Amit Sharma', 25, 'Delhi'),
(2, 'Priya Verma', 28, 'Mumbai'),
(3, 'Rahul Singh', 22, 'Lucknow'),
(4, 'Neha Gupta', 30, 'Jaipur'),
(5, 'Arjun Mehta', 27, 'Pune'),
(6, 'Sneha Reddy', 24, 'Hyderabad'),
(7, 'Vikas Yadav', 29, 'Patna'),
(8, 'Anjali Das', 26, 'Kolkata'),
(9, 'Rohit Kumar', 31, 'Chandigarh'),
(10, 'Kavita Joshi', 23, 'Bhopal');

SELECT * FROM PERSON;

ALTER TABLE PERSON
ADD COLUMN STREAM VARCHAR(50);
SELECT * FROM PERSON;

ALTER TABLE PERSON
DROP COLUMN AGE;

-- HOW TO RENAME COLUMN OR TABLE NAME :==

ALTER TABLE PERSON
RENAME COLUMN NAME  TO FNAME;

ALTER TABLE PERSON
RENAME TO PERSON_DETAILS;

SELECT * FROM PERSON_DETAILS;

-- HOW TO MODIFY COLUMN :==

ALTER TABLE PERSON_DETAILS
ALTER  COLUMN FNAME
SET DATA TYPE VARCHAR(60);

ALTER TABLE PERSON_DETAILS
ALTER COLUMN STREAM
SET DEFAULT 'UNKNOW';


-- CONSTRAINT CHECK :== USED TO DTA VALIDITY AND VERIFICATION OF DATA 

ALTER TABLE PERSON_DETAILS
ADD COLUMN
  MOB VARCHAR(15)
            CHECK( LENGTH(MOB) >= 10);

 ALTER TABLE PERSON_DETAILS
 DROP CONSTRAIT PERSON_DETAILS_MOB_CHECK;

-- NAME CONSTRAINT :== AT ERROR TIME PRINTS ON LOG








